export const FETCH_ALL_CHARACTERS = 'FETCH_ALL_CHARACTERS'
export const FETCH_ALL_CHARACTERS_SUCCESS = 'FETCH_ALL_CHARACTERS_SUCCESS'
export const FETCH_ALL_CHARACTERS_FAILURE = 'FETCH_ALL_CHARACTERS_FAILURE'

export const FETCH_PAGINATION_CHARACTERS = 'FETCH_PAGINATION_CHARACTERS'
export const FETCH_PAGINATION_CHARACTERS_SUCCESS =
  'FETCH_PAGINATION_CHARACTERS_SUCCESS'
export const FETCH_PAGINATION_CHARACTERS_FAILURE =
  'FETCH_PAGINATION_CHARACTERS_FAILURE'

export const FETCH_INDIVIDUAL_CHARACTERS = 'FETCH_INDIVIDUAL_CHARACTERS'
export const FETCH_INDIVIDUAL_CHARACTERS_SUCCESS =
  'FETCH_INDIVIDUAL_CHARACTERS_SUCCESS'
export const FETCH_INDIVIDUAL_CHARACTERS_FAILURE =
  'FETCH_INDIVIDUAL_CHARACTERS_FAILURE'

export const FETCH_QUOTES = 'FETCH_QUOTES'
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS'
export const FETCH_QUOTES_FAILURE = 'FETCH_QUOTES_FAILURE'

export const SEARCH_DATA = 'SEARCH_DATA'
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS'
export const SEARCH_DATA_FAILURE = 'SEARCH_DATA_FAILURE'
